### ISSUE TITLE
Please tell me how to merge translated japanese documents

### ISSUE THREAD

**Issue by magcho** [nuxsmin/sysPass-doc#16]
I have [translated to japanese documents](https://github.com/magcho/sysPass-doc/tree/translate_ja_jp/docs/locale/ja/LC_MESSAGES).

I want to merge [sysPass document page](https://syspass-doc.readthedocs.io/en/3.1/). I edited the "mo" and "po" files. Are there any other changes needed to merge?

**Comment by nuxsmin** [comment]
Hello,

many thanks for your contribution. PO files are the right one to be translated, so you only need to make a PR for make the translation available.

Regards
