### ISSUE TITLE
NGINX documentation

### ISSUE THREAD

**Issue by yycengbers** [nuxsmin/sysPass-doc#5]
Sent an email but didn't see a reply, so unsure if you received it.

>  I installed sysPass in two instances, and documented the process during the second install.
> 
> https://github.com/yycengbers/syspass-nginx
> 
> Any suggested edits are welcome of course.  This might help you with the NGINX questions that come up.

**Comment by nuxsmin** [comment]
Hello! 

So sorry about not replying to your email since I don't have the email account configured on my phone, so I can receive emails (just forwarded) but not reply to them...

I've starred your repo when received it :wink:

I've some side notes about the steps that I'll let you know by email.

Many thanks for your contribution!!

Kind regards

**Comment by yycengbers** [comment]
No problem.

My employees are accessing the instance, and our PC's are standardized and up-to-date.  If we didn't need a protocol or setting enabled on the server to access the database securely via Chrome, then I didn't include it (to the best of my understanding).  In this case, trying to keep things as secure as possible, I think less is more.

Because of that, I don't think the config will work across all phones and browsers, so I'll edit the description so readers understand this.  I don't know if I'll have time to work on a second set of instructions, at least not for a while.

Looking forward to your notes!

**Comment by nuxsmin** [comment]
Hello @yycengbers ,

this is my email sent on 19/4/3:

> Regarding your installation instructions, I really appreciate your efforts on it.
> 
> I've some side notes about them:
> 
>  * sysPass MySQL user does not need to have full privileges over all databases
>  * You need to allow to access to `/app` within `/etc/nginx/sites-available/default` since theme styles and fonts need to be got
>   * Composer installation need to be tweaked, since the installer's hash can change: https://getcomposer.org/doc/faqs/how-to-install-composer-programmatically.md
>   * Xdebug extension should be disabled in production environments
>   * Minor tweak: some "sed" commands can be written into one, so it would make the changes in a row
> 
> These steps will help me to build an Nginx based Docker image :)
> 
> That's all. Thanks so much for the great work!
> 
> Regards
