### ISSUE TITLE
API documentation: usergroup method is userGroup

### ISSUE THREAD

**Issue by juangarat** [nuxsmin/sysPass-doc#6]
nuxsmin, I'm testing syspass 3.0.5 docker image solution.
I'm developing python code to migrate accounts from CSV file and I was a few hours troubleshooting why this api request doesn't work

```
{
  "jsonrpc": "2.0",
  "method": "usergroup/search",
  "params": {
    "authToken": ""
  },
  "id": 1
}
```
API Response: 
`{'jsonrpc': '2.0', 'error': {'message': 'Oops, it looks like this content does not exist...', 'code': -32601, 'data': None}, 'id': 1}`

This is the API documentation
<img width="527" alt="image" src="https://user-images.githubusercontent.com/35067502/55600363-12637500-5732-11e9-80cf-fb08ce7ba3d3.png">

Finally, analyzing the code found that all references are **userGroup** with case G. 

This works!
```
{
  "jsonrpc": "2.0",
  "method": "userGroup/search",
  "params": {
    "authToken": ""
  },
  "id": 1
}
```

Can you please fix this in docs?

Thanks!

Juan

**Comment by nuxsmin** [comment]
Oops, sorry I'll fix it shortly.

Thanks for the feedback!

Regards

**Comment by nuxsmin** [comment]
Done :wink:
