### ISSUE TITLE
The master password can be on the server (in encrypted form)

### ISSUE THREAD

**Issue by gizezero** [nuxsmin/sysPass-doc#7]
Found inconsistency in docs:
https://doc.syspass.org/en/3.0/ :
"It **does not store** the master password in the **server**"

https://doc.syspass.org/en/3.0/application/encryption.html :
After logging in with the master password, it’s **encrypted and stored** within the user’s data in the **database**.

**Comment by nuxsmin** [comment]
Hello, it could be more accurate to say that the password isn't stored in plain text, but it's the truth that the password isn't stored, since it's encrypted and stored in the database, which might be installed in other server.

Regards

**Comment by gizezero** [comment]
Hello Rubén, thanks for answer.
The database server is also a server. 
I think that, If you store something in encrypted, possible to decrypt form, you still  store it.

**Comment by nuxsmin** [comment]
Done :wink: 

https://syspass-doc.readthedocs.io/en/3.1/index.html

Thanks for the feedback!
