### ISSUE TITLE
prevents to send sensitive date through plain channels

### ISSUE THREAD

**Issue by gizezero** [nuxsmin/sysPass-doc#8]
https://doc.syspass.org/en/3.0/application/encryption.html :

_In order to improve the security of the sent data, 
RSA (PKI) is being used for encrypting the passwords that are being sent from the application forms.
This prevents to send sensitive date through plain channels._

Prevents - but only in one direction - from client to server;
As I can see passwords are transferred from server to browser in open text.

**Comment by nuxsmin** [comment]
Hello, 

I'm always talking about sent data from the client side (application forms), so it does not imply from the server side.

Besides that some flow diagrams were made to clear up the security scheme.

Regards

**Comment by gizezero** [comment]
It's not clear for me that it's always about the client side.

I can't find plain password transferred from server to client on diagrams.

greetings

**Comment by nuxsmin** [comment]
Done :wink: 

https://syspass-doc.readthedocs.io/en/3.1/application/encryption.html

Thanks for the feedback!
